### ISSUE TITLE
Imrpove the exersice

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-hebebicho#1]
Awesome job @hebebicho  !!!

Here you have some tips to improve the exercise:

- [x] Fix the language of the page
- [x] Remove the extra `div` around the link of the logo and the title
- [x] Add `alt` attribute to the images.
- [x] Move the font CSS before your main CSS
- [x] Improve hierarchy, we can use the body tag selector to add general styles, like color, background-color, font-family, font-size, and font-weight
- [x] Write sentences as you would do in Spanish, capitalize the first letter.
- [x] Increase `width` of the main title for the tablet version, to avoid little movement on 'Diversidad' word.
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs

Let me know if you have any doubts ;)

Go for it!!

**Comment by hebebicho** [comment]
Hello @nasivuela !
Thank you for your ideas :)
When you said " Write sentences as you would do in Spanish, capitalize the first letter.", where do you mean? at my commits?
I made de main title div bigger, but I really can't see the little movement that you told me about, I hope we can talk about that in class, so I can consider those visual mistakes in future projects.

**Comment by nasivuela** [comment]
Ey! Glad to see that you are already working on this.

About your first doubt, what I meant is that 'creando diversidad digital' would be better as 'Creando diversidad digital'.

The second point it's already fixed, when the div was smaller the word 'Diversidad' was slightly moved to the right on tablet version, this was the look of it:

![Screenshot from 2019-03-14 23-30-48](https://user-images.githubusercontent.com/8023938/54395847-46a6c100-46b1-11e9-8be2-88fd1e03102a.png)

**Comment by hebebicho** [comment]
Hello again @nasivuela !
thanks for your feedback. 
I think I have made all the improvements that you suggested :)
Could you tell me if I did properly the hierarchy changes? 

thanks for everything :)
Elvira

**Comment by nasivuela** [comment]
Super @hebebicho !!!!
To make it perfect check out the logo on the mobile version. It should be separated from the top ;)
But this is a really good job, so I'm closing the issue.

![](https://media.giphy.com/media/3o6wrw8nj9ZjKBW1ZS/giphy.gif)
